redis_hostname: redis_hostname
redis_port: redis_port
input_queue_name: input_queue
worker_queue_name: worker_queue
result_queue_name: result_queue
output_queue_name: output_queue
emitter_control_syn_queue_name: emitter_control_syn_queue
worker_control_syn_queue_name: worker_control_syn_queue
worker_control_ack_queue_name: worker_control_ack_queue
collector_control_syn_queue_name: collector_control_syn_queue
emitter_start_queue_name: emitter_start_queue
worker_start_queue_name: worker_start_queue
collector_start_queue_name: collector_start_queue
wait_time: 0.1
processing_delay: 2
deadline_coeff: 2.5e-7
deadline_cap: 30
deadline_floor: 1
function_invoke_timeout: 10
function_invoke_retries: 6
scale_down_timeout: 10
scale_down_retries: 3