version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
  # gateway: $OPENFAAS_GATEWAY
functions:
  emitter:
    lang: python3-http
    handler: ./emitter
    image: lilanpei/emitter:latest
    # image: $USERID/$IMAGE_NAME:$TAG
    environment:
      read_timeout: 1h   # Time to read HTTP request
      write_timeout: 1h  # Time to write HTTP response
      exec_timeout: 1h   # Maximum execution time
      redis_hostname: "redis-master.redis.svc.cluster.local"
      redis_port: 6379
    annotations: # ESSENTIAL for a long-running worker
      com.openfaas.scale.min: "1"
      com.openfaas.schedule: "*/1 * * * *"

  worker:
    lang: python3-http
    handler: ./worker
    image: lilanpei/worker:latest
    # image: $USERID/$IMAGE_NAME:$TAG
    environment:
      read_timeout: 1h   # Time to read HTTP request
      write_timeout: 1h  # Time to write HTTP response
      exec_timeout: 1h   # Maximum execution time
      redis_hostname: "redis-master.redis.svc.cluster.local"
      redis_port: 6379
    annotations: # ESSENTIAL for a long-running worker
      com.openfaas.scale.min: "1"
      com.openfaas.schedule: "*/1 * * * *"

  collector:
    lang: python3-http
    handler: ./collector
    image: lilanpei/collector:latest
    # image: $USERID/$IMAGE_NAME:$TAG
    environment:
      read_timeout: 1h   # Time to read HTTP request
      write_timeout: 1h  # Time to write HTTP response
      exec_timeout: 1h   # Maximum execution time
      redis_hostname: "redis-master.redis.svc.cluster.local"
      redis_port: 6379
    annotations: # ESSENTIAL for a long-running worker
      com.openfaas.scale.min: "1"
      com.openfaas.schedule: "*/1 * * * *"

configuration:
  templates:
    - name: python3-http
      source: https://github.com/openfaas/python3-http-template
