version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
  # gateway: $OPENFAAS_GATEWAY
functions:
  emitter:
    lang: python3-http-skeleton
    handler: ./emitter
    image: lilanpei/emitter:latest
    # image: $USERID/$IMAGE_NAME:$TAG
    environment:
      read_timeout: 12h   # Time to read HTTP request
      write_timeout: 12h  # Time to write HTTP response
      exec_timeout: 12h   # Maximum execution time
      redis_hostname: "redis-master.redis.svc.cluster.local"
      redis_port: 6379
    annotations: # ESSENTIAL for a long-running worker
      com.openfaas.scale.min: "1"
      com.openfaas.retry.attempts: "0"
    resources:
      requests:
        cpu: "10m"
        memory: "20Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"

  worker:
    lang: python3-http-skeleton
    handler: ./worker
    image: lilanpei/worker:latest
    # image: $USERID/$IMAGE_NAME:$TAG
    environment:
      read_timeout: 12h   # Time to read HTTP request
      write_timeout: 12h  # Time to write HTTP response
      exec_timeout: 12h   # Maximum execution time
      redis_hostname: "redis-master.redis.svc.cluster.local"
      redis_port: 6379
    annotations: # ESSENTIAL for a long-running worker
      com.openfaas.scale.min: "1"
      com.openfaas.retry.attempts: "0"
    resources:
      requests:
        cpu: "10m"
        memory: "20Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"

  collector:
    lang: python3-http-skeleton
    handler: ./collector
    image: lilanpei/collector:latest
    # image: $USERID/$IMAGE_NAME:$TAG
    environment:
      read_timeout: 12h   # Time to read HTTP request
      write_timeout: 12h  # Time to write HTTP response
      exec_timeout: 12h   # Maximum execution time
      redis_hostname: "redis-master.redis.svc.cluster.local"
      redis_port: 6379
    annotations: # ESSENTIAL for a long-running worker
      com.openfaas.scale.min: "1"
      com.openfaas.retry.attempts: "0"
    resources:
      requests:
        cpu: "10m"
        memory: "20Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"

configuration:
  templates:
    - name: python3-http-skeleton
      source: https://github.com/lilanpei/AI-based-Autonomic-Management-of-Structured-Parallel-Programs/openfaas-functions/template/python3-http-skeleton
